### ISSUE TITLE
[registry] [poly_storage] copying storage without .prepare() causes segfault

### ISSUE THREAD

**Issue by Green-Sky** [skypjack/entt#644]
Copying without `other.prepare<Type>()` causes a segfault in `other.storage(info)`.

Easily replicated by deleting the 2 `.prepare()` statements in https://github.com/skypjack/entt/blob/master/test/entt/entity/poly_storage.cpp#L121 .

**Comment by skypjack** [comment]
Oh, sorry, forgot to update the issue.
I pushed the example to `experimental`. Does it work for you?

**Comment by Green-Sky** [comment]
Looks good. Every time I learn something new about the custom storage. Still don't fully get it, though...
Anyway, didn't have full registry copy in the last two iterations, but will get back to custom storage when i get to the prediction/rollback logic. Hope i know what I'm doing when i get back to it. :D
